name: example
description: Example of Adaptive Cards.
homepage: https://github.com/freemansoft/Flutter-AdaptiveCards
version: 0.2.1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  flex_color_scheme: ^8.2.0

  url_launcher: ^6.3.1
  http: ^1.5.0
  #http: ^1.3.0

  flutter_adaptive_cards:
    path: ..
  format: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - lib/easy_card
    - lib/adaptive_card_string
    - lib/host_config
    - lib/activity_update
    - lib/samples/text_block/
    - lib/samples/image/
    - lib/samples/container/
    - lib/samples/column_set/
    - lib/samples/column/
    - lib/samples/fact_set/
    - lib/samples/image_set/
    - lib/samples/action_set/
    - lib/samples/action_open_url/
    - lib/samples/action_submit/
    - lib/samples/action_show_card/
    - lib/samples/inputs/input_text/
    - lib/samples/inputs/input_number/
    - lib/samples/inputs/input_date/
    - lib/samples/inputs/input_time/
    - lib/samples/inputs/input_toggle/
    - lib/samples/inputs/input_choice_set/
    - lib/samples/media/example1.json
    - lib/samples/examples/
    - lib/samples/table/
    - lib/samples/v1.6/

publish_to: none
