name: flutter_adaptive_cards
description: Adaptive Cards are platform-agnostic snippets of UI, authored in JSON, that apps and services can openly exchange.
version: 0.2.1
homepage: https://github.com/freemansoft/Flutter-AdaptiveCards

environment:
  sdk: ^3.8.1

dependencies:

  # Content
  ## Video player with controls
  chewie: ^1.4.0
  fl_chart: 1.0.0 # https://github.com/imaNNeo/fl_chart/issues/1986
  flutter:
    sdk: flutter

  ## Markdown renderer
  flutter_markdown: ^0.7.7+1
  flutter_riverpod: ^3.0.0
  format: ^1.5.0
  # General
  http: ^1.6.0
  ## Localization
  intl: ^0.20.2

  # Used for automatic color adjustment for dark theme
  tinycolor2: ^3.0.1
  uuid: ^4.5.1
  video_player: ^2.10.0

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  #test: ^1.26.3

flutter:
  uses-material-design: true
